require('theme')
require('opts')
require('mappings')
require('plugins')
require('anik.colorizer-setup')
require('anik.statusline-setup')
--require('anik.windline-setup')
require('explorer-setup')
require('anik.lspconfig-setup')
require('anik.treesitter-setup')
require('anik.compe-setup')
vim.cmd('source ~/.config/nvim/vim/start-screen.vim')
vim.cmd('source ~/.config/nvim/vim/floatterm.vim')
vim.cmd('source ~/.config/nvim/vim/fzf.vim')
vim.cmd('source ~/.config/nvim/vim/which-key.vim')
--vim.cmd('colo dracula')
